name: "KRED"
n_gpu: 1
data_loader:
    batch_size: 32
    shuffle: true
    num_workers: 1

data:
  train_news : "./datasets/mind_train_demo/news.tsv" #26740
  train_behavior : "./datasets/mind_train_demo/behaviors.tsv"
  valid_news : "./datasets/mind_val_demo/news.tsv"
  valid_behavior : "./datasets/mind_val_demo/behaviors.tsv"
  knowledge_graph : "./datasets/mind_utils_demo/triple2id.txt"
  entity_embedding : "./datasets/mind_utils_demo/entity2vecd100.vec"
  num_entity_embedding: 3275150
  relation_embedding : "./datasets/mind_utils_demo/relation2vecd100.vec"
  entity_index : "./datasets/mind_utils_demo/entity2id.txt"
  relation_index : "./datasets/mind_utils_demo/relation2id.txt"
  sparse_adj_entity : "./datasets/mind_utils_demo/entity_adj.npy"
  sparse_adj_relation : "./datasets/mind_utils_demo/relation_adj.npy"
  mind_data : "./data_dict_1672848868384.pkl"

jobs:
  train_jobs : "./datasets/LinkedIn-Tech-Job-Data/train_jobs.tsv"
  train_behavior : "./datasets/LinkedIn-Tech-Job-Data/behaviors_train_jobs.tsv"
  valid_jobs : "./datasets/LinkedIn-Tech-Job-Data/valid_jobs.tsv"
  valid_behavior : "./datasets/LinkedIn-Tech-Job-Data/behaviors_valid_jobs.tsv"
  knowledge_graph : "./datasets/LinkedIn-Tech-Job-Data/triple2id_jobs.txt"
  entity_embedding : "./datasets/LinkedIn-Tech-Job-Data/entity2vecd100_jobs.vec"
  num_entity_embedding: 13355
  wikidata_ids: "./datasets/LinkedIn-Tech-Job-Data/wikidata_ids.txt"
  relation_embedding : "./datasets/LinkedIn-Tech-Job-Data/relation2vecd100_jobs.vec"
  entity_index : "./datasets/LinkedIn-Tech-Job-Data/entity2id_jobs.txt"
  relation_index : "./datasets/LinkedIn-Tech-Job-Data/relation2id_jobs.txt"
  #sparse_adj_entity : "./datasets/LinkedIn-Tech-Job-Data/entity_adj.npy"
  #sparse_adj_relation : "./datasets/LinkedIn-Tech-Job-Data/relation_adj.npy"
  jobs_data : "./data_dict_jobs_1676475431977.pkl"

model:
  document_embedding_dim: 768
  embedding_dim: 100
  news_entity_num: 20
  entity_neighbor_num: 20
  entity_embedding_dim: 100
  layer_dim: 128
  user_his_num: 20


trainer:
  training_type: "single_task" # single_task or multi-task
  task: "user2item" # task should be within: user2item, item2item, vert_classify, pop_predict
  epochs: 5
  smooth_lamda: 10
  train_neg_num: 4
  save_dir: "./out/saved/"
  save_period: 1
  early_stop: 3
  monitor: "val_auc"
  verbosity: 2

optimizer:
  type: "Adam"
  lr: 0.00002
  weight_decay: 0.000001
  amsgrad: true
