name: "KRED"
n_gpu: 1
data_loader:
    batch_size: 128
    shuffle: true
    num_workers: 1

data:
  train_news : "./adressa/mind_format/train/news_no_eng_entities.tsv"
  train_behavior : "./adressa/mind_format/train/behaviors.tsv"
  valid_news : "./adressa/mind_format/valid/news_no_eng_entities.tsv"
  valid_behavior : "./adressa/mind_format/valid/behaviors.tsv"
  knowledge_graph : "./adressa/kg/triple2id_jobs.txt"
  entity_embedding : "./adressa/kg/entity2vecd100_jobs.vec"
  num_entity_embedding: 4567
  relation_embedding : "./adressa/kg/relation2vecd100_jobs.vec"
  entity_index : "./adressa/kg/entity2id_jobs.txt"
  relation_index : "./adressa/kg/relation2id_jobs.txt"
  sparse_adj_entity : ""
  sparse_adj_relation : ""
  mind_data : ""

model:
  document_embedding_dim: 768
  embedding_dim: 100
  news_entity_num: 20
  entity_neighbor_num: 20
  entity_embedding_dim: 100
  layer_dim: 128
  user_his_num: 20


trainer:
  training_type: "single_task" # single_task or multi-task
  task: "user2item" # task should be within: user2item, item2item, vert_classify, pop_predict
  epochs: 20
  smooth_lamda: 10
  train_neg_num: 4
  save_dir: "./out/saved/"
  save_period: 1
  early_stop: 3
  monitor: "val_auc"
  verbosity: 2

optimizer:
  type: "Adam"
  lr: 0.00002
  weight_decay: 0.000001
  amsgrad: true